---
- name: Provision Arch Linux image
  hosts: all
  become: true
  gather_facts: true
  roles:
    - archlinux/mirrors
    - archlinux/keyring
    - common/base
    - common/vagrant_user
    - common/cleanup
